services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - postgres_to_do_data:/var/lib/postgresql/data

volumes:
  postgres_to_do_data: